import { Theme } from './types';

/**
 * Registry of all themes.
 * Each theme is a COMPLETE visual identity — not just colors.
 * Changing a theme should feel like switching to an entirely different website.
 */
export const THEME_REGISTRY: Record<string, Theme> = {
  // =========================================================================
  // MODERN / CLEAN
  // =========================================================================
  'apple-modern': {
    id: 'apple-modern',
    name: 'Apple Modern',
    description: 'Clean, precise, and premium. Whitespace and subtle depth define this look.',
    category: 'Modern',
    tokens: {
      colors: {
        primary: 'hsl(210 20% 15%)',
        primaryForeground: 'hsl(210 20% 98%)',
        accent: 'hsl(210 20% 40%)',
        accentForeground: 'hsl(210 20% 98%)',
        background: 'hsl(0 0% 100%)',
        foreground: 'hsl(210 20% 10%)',
        secondary: 'hsl(210 20% 96%)',
        secondaryForeground: 'hsl(210 20% 20%)',
        muted: 'hsl(210 20% 90%)',
        mutedForeground: 'hsl(210 20% 40%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(210 20% 10%)',
        border: 'hsl(210 20% 90%)',
        input: 'hsl(210 20% 90%)',
        ring: 'hsl(210 20% 30%)',
      },
      typography: {
        headingFont: 'SF Pro Display, Inter, sans-serif',
        bodyFont: 'SF Pro Text, Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '-0.02em',
      },
      visuals: {
        radius: '1.25rem',
        shadow: '0 4px 24px 0 rgba(0, 0, 0, 0.04)',
        glassEffect: 'soft',
        borderStyle: 'thin',
        borderRadius: 'lg',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'linear-gradient(180deg, #FFFFFF 0%, #F5F5F7 100%)',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'minimal',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'glass', border: '1px solid rgba(0, 0, 0, 0.05)', shadow: '0 8px 32px rgba(0, 0, 0, 0.08)' },
        button: { style: 'apple', transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)' },
        timeline: { style: 'vertical', markerStyle: 'dot' },
        gallery: { style: 'grid', gap: '1.5rem' },
        rsvp: { style: 'step-by-step' },
        footer: { style: 'modern' },
      },
    },
  },
  'apple-event': {
    id: 'apple-event',
    name: 'Apple Event',
    description: 'Dramatic dark mode with vibrant gradients and bold typography. Inspired by Apple keynotes.',
    category: 'Modern',
    tokens: {
      colors: {
        primary: 'hsl(210 80% 60%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(310 80% 60%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(0 0% 5%)',
        foreground: 'hsl(0 0% 95%)',
        secondary: 'hsl(0 0% 12%)',
        secondaryForeground: 'hsl(0 0% 80%)',
        muted: 'hsl(0 0% 20%)',
        mutedForeground: 'hsl(0 0% 60%)',
        card: 'hsl(0 0% 8%)',
        cardForeground: 'hsl(0 0% 95%)',
        border: 'hsl(0 0% 25%)',
        input: 'hsl(0 0% 25%)',
        ring: 'hsl(210 80% 60%)',
      },
      typography: {
        headingFont: 'SF Pro Display, Inter, sans-serif',
        bodyFont: 'SF Pro Text, Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '-0.01em',
      },
      visuals: {
        radius: '0.75rem',
        shadow: '0 10px 40px rgba(0, 0, 0, 0.6)',
        glassEffect: 'strong',
        borderStyle: 'thin',
        borderRadius: 'md',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'radial-gradient(ellipse at top, #1a1a2e 0%, #0a0a0a 100%)',
        texture: 'texture-noise',
        accentPattern: '',
        sectionDecoration: 'gradient-line',
        particleEffect: 'sparkles',
      },
      components: {
        card: { style: 'glass', border: '1px solid rgba(255,255,255,0.08)', shadow: '0 20px 60px rgba(0,0,0,0.5)' },
        button: { style: 'apple', transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)' },
        timeline: { style: 'vertical', markerStyle: 'dot' },
        gallery: { style: 'carousel', gap: '1rem' },
        rsvp: { style: 'step-by-step' },
        footer: { style: 'modern' },
      },
    },
  },
  'modern-minimal': {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    description: 'Pure minimalism. Black, white, and careful spacing. Nothing extra.',
    category: 'Modern',
    tokens: {
      colors: {
        primary: 'hsl(0 0% 7%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(0 0% 50%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(0 0% 100%)',
        foreground: 'hsl(0 0% 7%)',
        secondary: 'hsl(0 0% 95%)',
        secondaryForeground: 'hsl(0 0% 20%)',
        muted: 'hsl(0 0% 90%)',
        mutedForeground: 'hsl(0 0% 45%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(0 0% 7%)',
        border: 'hsl(0 0% 90%)',
        input: 'hsl(0 0% 90%)',
        ring: 'hsl(0 0% 30%)',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '400',
        bodyWeight: '400',
        letterSpacing: '0em',
      },
      visuals: {
        radius: '0rem',
        shadow: '0 1px 3px rgba(0, 0, 0, 0.08)',
        glassEffect: 'none',
        borderStyle: 'thin',
        borderRadius: 'none',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'none',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'minimal',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'minimal', border: '1px solid hsl(0 0% 90%)', shadow: 'none' },
        button: { style: 'sharp', transition: 'all 0.15s ease' },
        timeline: { style: 'minimal', markerStyle: 'dot' },
        gallery: { style: 'grid', gap: '0.5rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'modern' },
      },
    },
  },
  'minimal-white': {
    id: 'minimal-white',
    name: 'Minimal White',
    description: 'Bright, airy, and immaculate. Perfect for showcasing photography.',
    category: 'Modern',
    tokens: {
      colors: {
        primary: 'hsl(0 0% 7%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(25 10% 80%)',
        accentForeground: 'hsl(0 0% 7%)',
        background: 'hsl(0 0% 100%)',
        foreground: 'hsl(0 0% 7%)',
        secondary: 'hsl(0 0% 42%)',
        secondaryForeground: 'hsl(0 0% 7%)',
        muted: 'hsl(0 0% 90%)',
        mutedForeground: 'hsl(0 0% 30%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(0 0% 7%)',
        border: 'hsl(0 0% 90%)',
        input: 'hsl(0 0% 90%)',
        ring: 'hsl(25 10% 80%)',
      },
      typography: {
        headingFont: 'Cormorant Garamond, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '300',
        bodyWeight: '400',
        letterSpacing: '0.02em',
      },
      visuals: {
        radius: '0rem',
        shadow: '0 2px 16px 0 rgba(0,0,0,0.04)',
        glassEffect: 'none',
        borderStyle: 'thin',
        borderRadius: 'none',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'none',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'thin-line',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'flat', border: '1px solid hsl(0 0% 90%)', shadow: 'none' },
        button: { style: 'apple', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'dot' },
        gallery: { style: 'masonry', gap: '1rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'modern' },
      },
    },
  },
  'instagram-story': {
    id: 'instagram-story',
    name: 'Instagram Story',
    description: 'Vertical-first, vibrant gradients, bold text overlays. Like an Instagram story come to life.',
    category: 'Modern',
    tokens: {
      colors: {
        primary: 'hsl(330 70% 50%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(200 80% 60%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(200 80% 90%)',
        foreground: 'hsl(0 0% 10%)',
        secondary: 'hsl(330 70% 95%)',
        secondaryForeground: 'hsl(330 70% 20%)',
        muted: 'hsl(0 0% 85%)',
        mutedForeground: 'hsl(0 0% 40%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(0 0% 10%)',
        border: 'hsl(0 0% 80%)',
        input: 'hsl(0 0% 80%)',
        ring: 'hsl(330 70% 50%)',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '800',
        bodyWeight: '400',
        letterSpacing: '-0.03em',
      },
      visuals: {
        radius: '2rem',
        shadow: '0 15px 50px rgba(0, 0, 0, 0.15)',
        glassEffect: 'none',
        borderStyle: 'none',
        borderRadius: 'full',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 50%, #4facfe 100%)',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'gradient-line',
        particleEffect: 'bubbles',
      },
      components: {
        card: { style: 'glass', border: '1px solid rgba(255,255,255,0.3)', shadow: '0 10px 40px rgba(0,0,0,0.1)' },
        button: { style: 'pill', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'circle' },
        gallery: { style: 'carousel', gap: '1rem' },
        rsvp: { style: 'step-by-step' },
        footer: { style: 'modern' },
      },
    },
  },
  'pinterest': {
    id: 'pinterest',
    name: 'Pinterest',
    description: 'Warm, aspirational, and highly visual. Masonry layout with rich textures.',
    category: 'Modern',
    tokens: {
      colors: {
        primary: 'hsl(0 60% 30%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(30 80% 50%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(0 0% 98%)',
        foreground: 'hsl(0 0% 15%)',
        secondary: 'hsl(0 0% 93%)',
        secondaryForeground: 'hsl(0 0% 25%)',
        muted: 'hsl(0 0% 88%)',
        mutedForeground: 'hsl(0 0% 50%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(0 0% 15%)',
        border: 'hsl(0 0% 85%)',
        input: 'hsl(0 0% 85%)',
        ring: 'hsl(0 60% 30%)',
      },
      typography: {
        headingFont: 'Playfair Display, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.02em',
      },
      visuals: {
        radius: '1.5rem',
        shadow: '0 8px 30px rgba(0, 0, 0, 0.08)',
        glassEffect: 'none',
        borderStyle: 'none',
        borderRadius: 'lg',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'none',
        texture: 'paper-texture',
        accentPattern: '',
        sectionDecoration: 'minimal',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'flat', border: 'none', shadow: '0 4px 16px rgba(0,0,0,0.06)' },
        button: { style: 'pill', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'circle' },
        gallery: { style: 'masonry', gap: '1.5rem' },
        rsvp: { style: 'form' },
        footer: { style: 'modern' },
      },
    },
  },

  'basic-white': {
    id: 'basic-white',
    name: 'Basic White',
    description: 'A clean, stark white background with subtle grey text. The simplest, most neutral canvas.',
    category: 'Modern',
    tokens: {
      colors: {
        primary: 'hsl(210 20% 25%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(210 20% 50%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(0 0% 100%)',
        foreground: 'hsl(210 20% 20%)',
        secondary: 'hsl(210 20% 95%)',
        secondaryForeground: 'hsl(210 20% 25%)',
        muted: 'hsl(210 20% 90%)',
        mutedForeground: 'hsl(210 20% 40%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(210 20% 20%)',
        border: 'hsl(210 10% 88%)',
        input: 'hsl(210 10% 88%)',
        ring: 'hsl(210 20% 25%)',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0em',
      },
      visuals: {
        radius: '0.5rem',
        shadow: '0 2px 10px rgba(0, 0, 0, 0.03)',
        glassEffect: 'none',
        borderStyle: 'thin',
        borderRadius: 'md',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'none',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'none',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'minimal', border: '1px solid hsl(210 10% 88%)', shadow: 'none' },
        button: { style: 'minimal', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'dot' },
        gallery: { style: 'grid', gap: '1rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'minimal' },
      },
    },
  },

  // =========================================================================
  // LUXURY
  // =========================================================================
  'luxury-black': {
    id: 'luxury-black',
    name: 'Luxury Black',
    description: 'High contrast, deep blacks, and gold accents. The pinnacle of elegance.',
    category: 'Luxury',
    tokens: {
      colors: {
        primary: 'hsl(45 40% 60%)',
        primaryForeground: 'hsl(0 0% 5%)',
        accent: 'hsl(45 40% 80%)',
        accentForeground: 'hsl(0 0% 5%)',
        background: 'hsl(0 0% 3%)',
        foreground: 'hsl(45 40% 95%)',
        secondary: 'hsl(0 0% 10%)',
        secondaryForeground: 'hsl(45 40% 90%)',
        muted: 'hsl(0 0% 15%)',
        mutedForeground: 'hsl(45 40% 60%)',
        card: 'hsl(0 0% 7%)',
        cardForeground: 'hsl(45 40% 95%)',
        border: 'hsl(45 40% 20%)',
        input: 'hsl(45 40% 20%)',
        ring: 'hsl(45 40% 60%)',
      },
      typography: {
        headingFont: 'Playfair Display, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '0.05em',
      },
      visuals: {
        radius: '0.5rem',
        shadow: '0 10px 40px rgba(0, 0, 0, 0.8)',
        glassEffect: 'strong',
        borderStyle: 'thin',
        borderRadius: 'sm',
      },
      identity: {
        backgroundPattern: 'pattern-dark-luxury',
        backgroundGradient: 'radial-gradient(circle at center, #1a1a1a 0%, #000000 100%)',
        texture: 'texture-grain',
        accentPattern: 'border-gold-linear',
        sectionDecoration: 'gold-line',
        particleEffect: 'sparkles',
      },
      components: {
        card: { style: 'luxury', border: '1px solid hsl(45 40% 30%)', shadow: '0 20px 50px rgba(0, 0, 0, 0.9)' },
        button: { style: 'luxury', transition: 'all 0.3s ease' },
        timeline: { style: 'zigzag', markerStyle: 'diamond' },
        gallery: { style: 'masonry', gap: '2rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'luxury' },
      },
    },
  },
  'elegant-gold': {
    id: 'elegant-gold',
    name: 'Elegant Gold',
    description: 'Warm champagne tones with golden accents. Classic luxury.',
    category: 'Luxury',
    tokens: {
      colors: {
        primary: 'hsl(38 55% 58%)',
        primaryForeground: 'hsl(25 15% 18%)',
        accent: 'hsl(38 65% 52%)',
        accentForeground: 'hsl(38 60% 12%)',
        background: 'hsl(40 35% 97%)',
        foreground: 'hsl(25 15% 18%)',
        secondary: 'hsl(36 25% 91%)',
        secondaryForeground: 'hsl(25 15% 25%)',
        muted: 'hsl(30 20% 88%)',
        mutedForeground: 'hsl(25 10% 45%)',
        card: 'hsl(38 30% 96%)',
        cardForeground: 'hsl(25 15% 18%)',
        border: 'hsl(36 18% 82%)',
        input: 'hsl(36 18% 82%)',
        ring: 'hsl(38 55% 52%)',
      },
      typography: {
        headingFont: 'Playfair Display, Cormorant Garamond, serif',
        bodyFont: 'Cormorant Garamond, serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Battambang, serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.08em',
      },
      visuals: {
        radius: '1rem',
        shadow: '0 8px 32px rgba(180, 140, 80, 0.15)',
        glassEffect: 'soft',
        borderStyle: 'thin',
        borderRadius: 'md',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'linear-gradient(180deg, #FDFBF7 0%, #F8F4EE 50%, #F4EEE4 100%)',
        texture: 'paper-texture',
        accentPattern: 'gold-border',
        sectionDecoration: 'divider-flourish',
        particleEffect: 'sparkles',
      },
      components: {
        card: { style: 'luxury', border: '1px solid hsl(38 55% 70%)', shadow: '0 8px 32px rgba(180,140,80,0.1)' },
        button: { style: 'luxury', transition: 'all 0.3s ease' },
        timeline: { style: 'vertical', markerStyle: 'diamond' },
        gallery: { style: 'grid', gap: '1rem' },
        rsvp: { style: 'form' },
        footer: { style: 'luxury' },
      },
    },
  },
  'european-luxury': {
    id: 'european-luxury',
    name: 'European Luxury',
    description: 'Refined European elegance. Muted blush, gold, and classic serif typography.',
    category: 'Luxury',
    tokens: {
      colors: {
        primary: 'hsl(345 45% 72%)',
        primaryForeground: 'hsl(345 30% 15%)',
        accent: 'hsl(38 65% 52%)',
        accentForeground: 'hsl(38 60% 12%)',
        background: 'hsl(42 40% 96%)',
        foreground: 'hsl(25 15% 18%)',
        secondary: 'hsl(36 25% 91%)',
        secondaryForeground: 'hsl(25 15% 25%)',
        muted: 'hsl(30 20% 88%)',
        mutedForeground: 'hsl(25 10% 45%)',
        card: 'hsl(40 35% 95%)',
        cardForeground: 'hsl(25 15% 18%)',
        border: 'hsl(36 18% 80%)',
        input: 'hsl(36 18% 80%)',
        ring: 'hsl(345 45% 65%)',
      },
      typography: {
        headingFont: 'Cormorant Garamond, Playfair Display, serif',
        bodyFont: 'Cormorant Garamond, serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Battambang, serif',
        headingWeight: '500',
        bodyWeight: '400',
        letterSpacing: '0.06em',
      },
      visuals: {
        radius: '1.5rem',
        shadow: '0 10px 40px rgba(100, 80, 60, 0.1)',
        glassEffect: 'soft',
        borderStyle: 'thin',
        borderRadius: 'lg',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'linear-gradient(180deg, #FAF6F1 0%, #F5F0EA 100%)',
        texture: 'linen-texture',
        accentPattern: 'gold-border',
        sectionDecoration: 'divider-flourish',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'luxury', border: '1px solid hsl(36 18% 82%)', shadow: '0 8px 40px rgba(100,80,60,0.08)' },
        button: { style: 'pill', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'diamond' },
        gallery: { style: 'grid', gap: '1.5rem' },
        rsvp: { style: 'form' },
        footer: { style: 'classic' },
      },
    },
  },
  'dark-luxury': {
    id: 'dark-luxury',
    name: 'Dark Luxury',
    description: 'Sleek, dark, and opulent. Deep charcoal with warm metallic accents.',
    category: 'Luxury',
    tokens: {
      colors: {
        primary: 'hsl(35 30% 80%)',
        primaryForeground: 'hsl(0 0% 5%)',
        accent: 'hsl(35 50% 60%)',
        accentForeground: 'hsl(0 0% 5%)',
        background: 'hsl(0 0% 8%)',
        foreground: 'hsl(35 30% 90%)',
        secondary: 'hsl(0 0% 14%)',
        secondaryForeground: 'hsl(35 20% 80%)',
        muted: 'hsl(0 0% 20%)',
        mutedForeground: 'hsl(35 15% 60%)',
        card: 'hsl(0 0% 10%)',
        cardForeground: 'hsl(35 30% 90%)',
        border: 'hsl(35 20% 25%)',
        input: 'hsl(35 20% 25%)',
        ring: 'hsl(35 50% 60%)',
      },
      typography: {
        headingFont: 'Playfair Display, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.04em',
      },
      visuals: {
        radius: '0.75rem',
        shadow: '0 15px 50px rgba(0, 0, 0, 0.8)',
        glassEffect: 'strong',
        borderStyle: 'thin',
        borderRadius: 'md',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'linear-gradient(180deg, #1a1a1a 0%, #0d0d0d 100%)',
        texture: 'texture-grain',
        accentPattern: '',
        sectionDecoration: 'gold-line',
        particleEffect: 'sparkles',
      },
      components: {
        card: { style: 'glass', border: '1px solid hsl(35 20% 20%)', shadow: '0 20px 60px rgba(0,0,0,0.6)' },
        button: { style: 'luxury', transition: 'all 0.3s ease' },
        timeline: { style: 'vertical', markerStyle: 'diamond' },
        gallery: { style: 'grid', gap: '1rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'luxury' },
      },
    },
  },
  'fashion': {
    id: 'fashion',
    name: 'Fashion',
    description: 'Bold, editorial, and trend-forward. High contrast with punchy typography.',
    category: 'Luxury',
    tokens: {
      colors: {
        primary: 'hsl(0 0% 10%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(350 80% 60%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(0 0% 100%)',
        foreground: 'hsl(0 0% 10%)',
        secondary: 'hsl(0 0% 90%)',
        secondaryForeground: 'hsl(0 0% 20%)',
        muted: 'hsl(0 0% 85%)',
        mutedForeground: 'hsl(0 0% 50%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(0 0% 10%)',
        border: 'hsl(0 0% 80%)',
        input: 'hsl(0 0% 80%)',
        ring: 'hsl(350 80% 60%)',
      },
      typography: {
        headingFont: 'Playfair Display, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '0.1em',
      },
      visuals: {
        radius: '0rem',
        shadow: '0 4px 20px rgba(0, 0, 0, 0.06)',
        glassEffect: 'none',
        borderStyle: 'thick',
        borderRadius: 'none',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'none',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'bold-line',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'flat', border: '2px solid hsl(0 0% 90%)', shadow: 'none' },
        button: { style: 'sharp', transition: 'all 0.15s ease' },
        timeline: { style: 'horizontal', markerStyle: 'circle' },
        gallery: { style: 'grid', gap: '0rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'modern' },
      },
    },
  },

  // =========================================================================
  // TRADITIONAL / CULTURAL
  // =========================================================================
  'khmer-traditional': {
    id: 'khmer-traditional',
    name: 'Khmer Traditional',
    description: 'Deep reds, gold, and royal ornaments. Honoring heritage.',
    category: 'Traditional',
    tokens: {
      colors: {
        primary: 'hsl(15 60% 30%)',
        primaryForeground: 'hsl(45 40% 95%)',
        accent: 'hsl(45 60% 50%)',
        accentForeground: 'hsl(15 60% 30%)',
        background: 'hsl(30 40% 96%)',
        foreground: 'hsl(15 60% 10%)',
        secondary: 'hsl(30 40% 85%)',
        secondaryForeground: 'hsl(15 60% 20%)',
        muted: 'hsl(30 30% 80%)',
        mutedForeground: 'hsl(15 60% 40%)',
        card: 'hsl(30 40% 98%)',
        cardForeground: 'hsl(15 60% 10%)',
        border: 'hsl(15 60% 40%)',
        input: 'hsl(15 60% 40%)',
        ring: 'hsl(45 60% 50%)',
      },
      typography: {
        headingFont: 'Moul, serif',
        bodyFont: 'Battambang, serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Battambang, serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '0.02em',
      },
      visuals: {
        radius: '0.75rem',
        shadow: '0 10px 30px rgba(15, 60, 10, 0.1)',
        glassEffect: 'none',
        borderStyle: 'double',
        borderRadius: 'md',
      },
      identity: {
        backgroundPattern: 'pattern-khmer-ornament',
        backgroundGradient: 'linear-gradient(135deg, #FDFBF7 0%, #F5EFE6 100%)',
        texture: 'paper-texture',
        accentPattern: 'khmer-border',
        sectionDecoration: 'khmer-divider',
        particleEffect: 'petals',
      },
      components: {
        card: { style: 'luxury', border: '2px solid hsl(45 60% 50%)', shadow: '0 15px 30px rgba(15, 60, 10, 0.15)' },
        button: { style: 'pill', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'circle' },
        gallery: { style: 'grid', gap: '1rem' },
        rsvp: { style: 'form' },
        footer: { style: 'classic' },
      },
    },
  },
  'modern-khmer-luxury': {
    id: 'modern-khmer-luxury',
    name: 'Modern Khmer Luxury',
    description: 'Traditional Khmer elegance expressed through modern design language.',
    category: 'Traditional',
    tokens: {
      colors: {
        primary: 'hsl(25 30% 20%)',
        primaryForeground: 'hsl(25 20% 15%)',
        accent: 'hsl(35 40% 70%)',
        accentForeground: 'hsl(25 20% 15%)',
        background: 'hsl(30 45% 98%)',
        foreground: 'hsl(25 20% 15%)',
        secondary: 'hsl(30 35% 92%)',
        secondaryForeground: 'hsl(25 20% 15%)',
        muted: 'hsl(30 25% 88%)',
        mutedForeground: 'hsl(25 15% 45%)',
        card: 'hsl(30 50% 100%)',
        cardForeground: 'hsl(25 20% 15%)',
        border: 'hsl(30 20% 85%)',
        input: 'hsl(30 20% 85%)',
        ring: 'hsl(25 30% 20%)',
      },
      typography: {
        headingFont: 'Kantumruy Pro, sans-serif',
        bodyFont: 'Battambang, serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Battambang, serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.01em',
      },
      visuals: {
        radius: '1rem',
        shadow: '0 8px 30px rgba(0, 0, 0, 0.06)',
        glassEffect: 'soft',
        borderStyle: 'thin',
        borderRadius: 'lg',
      },
      identity: {
        backgroundPattern: 'pattern-khmer-geometric',
        backgroundGradient: 'linear-gradient(135deg, #FAFAFA 0%, #F0EDE8 100%)',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'divider-flourish',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'glass', border: '1px solid hsl(30 20% 85%)', shadow: '0 8px 30px rgba(0,0,0,0.04)' },
        button: { style: 'pill', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'circle' },
        gallery: { style: 'grid', gap: '1rem' },
        rsvp: { style: 'form' },
        footer: { style: 'classic' },
      },
    },
  },
  'royal-palace': {
    id: 'royal-palace',
    name: 'Royal Palace',
    description: 'Opulent and majestic. Gold leaf, deep crimson, and royal ornamentation.',
    category: 'Traditional',
    tokens: {
      colors: {
        primary: 'hsl(0 80% 30%)',
        primaryForeground: 'hsl(45 100% 50%)',
        accent: 'hsl(45 100% 50%)',
        accentForeground: 'hsl(0 80% 15%)',
        background: 'hsl(30 30% 90%)',
        foreground: 'hsl(0 80% 10%)',
        secondary: 'hsl(45 50% 85%)',
        secondaryForeground: 'hsl(0 80% 20%)',
        muted: 'hsl(30 20% 80%)',
        mutedForeground: 'hsl(0 80% 30%)',
        card: 'hsl(45 40% 95%)',
        cardForeground: 'hsl(0 80% 10%)',
        border: 'hsl(45 100% 60%)',
        input: 'hsl(45 100% 60%)',
        ring: 'hsl(45 100% 50%)',
      },
      typography: {
        headingFont: 'Moul, Playfair Display, serif',
        bodyFont: 'Cormorant Garamond, serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Battambang, serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '0.12em',
      },
      visuals: {
        radius: '0.5rem',
        shadow: '0 15px 50px rgba(150, 0, 0, 0.2)',
        glassEffect: 'none',
        borderStyle: 'double',
        borderRadius: 'sm',
      },
      identity: {
        backgroundPattern: 'pattern-royal-ornament',
        backgroundGradient: 'radial-gradient(ellipse at center, #f5e6d3 0%, #e8d5c4 100%)',
        texture: 'texture-gold-foil',
        accentPattern: 'border-royal-gold',
        sectionDecoration: 'khmer-divider',
        particleEffect: 'sparkles',
      },
      components: {
        card: { style: 'luxury', border: '2px solid hsl(45 100% 50%)', shadow: '0 20px 60px rgba(150,0,0,0.15)' },
        button: { style: 'pill', transition: 'all 0.3s ease' },
        timeline: { style: 'zigzag', markerStyle: 'diamond' },
        gallery: { style: 'grid', gap: '1rem' },
        rsvp: { style: 'form' },
        footer: { style: 'classic' },
      },
    },
  },
  'japanese': {
    id: 'japanese',
    name: 'Japanese',
    description: 'Wabi-sabi. Minimal, natural, and serene. Cherry blossoms and ink washes.',
    category: 'Traditional',
    tokens: {
      colors: {
        primary: 'hsl(330 30% 22%)',
        primaryForeground: 'hsl(330 20% 17%)',
        accent: 'hsl(340 70% 85%)',
        accentForeground: 'hsl(330 20% 17%)',
        background: 'hsl(340 50% 98%)',
        foreground: 'hsl(330 20% 17%)',
        secondary: 'hsl(340 60% 80%)',
        secondaryForeground: 'hsl(330 20% 17%)',
        muted: 'hsl(335 30% 90%)',
        mutedForeground: 'hsl(330 15% 40%)',
        card: 'hsl(340 50% 97%)',
        cardForeground: 'hsl(330 20% 17%)',
        border: 'hsl(335 25% 85%)',
        input: 'hsl(335 25% 85%)',
        ring: 'hsl(340 70% 85%)',
      },
      typography: {
        headingFont: 'Noto Serif JP, serif',
        bodyFont: 'Noto Sans JP, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '400',
        bodyWeight: '300',
        letterSpacing: '0.15em',
      },
      visuals: {
        radius: '0.25rem',
        shadow: '0 2px 8px rgba(0, 0, 0, 0.04)',
        glassEffect: 'none',
        borderStyle: 'thin',
        borderRadius: 'sm',
      },
      identity: {
        backgroundPattern: 'pattern-cherry-blossom',
        backgroundGradient: 'linear-gradient(180deg, #FDF8FA 0%, #F8F0F4 100%)',
        texture: 'washi-paper',
        accentPattern: 'sumi-ink',
        sectionDecoration: 'thin-line',
        particleEffect: 'petals',
      },
      components: {
        card: { style: 'minimal', border: '1px solid hsl(335 25% 85%)', shadow: '0 2px 8px rgba(0,0,0,0.02)' },
        button: { style: 'apple', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'circle' },
        gallery: { style: 'grid', gap: '0.5rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'modern' },
      },
    },
  },
  'korean': {
    id: 'korean',
    name: 'Korean',
    description: 'Hallyu elegance. Clean, sophisticated, with subtle pastel tones and refined details.',
    category: 'Traditional',
    tokens: {
      colors: {
        primary: 'hsl(25 10% 23%)',
        primaryForeground: 'hsl(20 10% 17%)',
        accent: 'hsl(20 60% 85%)',
        accentForeground: 'hsl(20 10% 17%)',
        background: 'hsl(25 40% 97%)',
        foreground: 'hsl(20 10% 17%)',
        secondary: 'hsl(200 10% 78%)',
        secondaryForeground: 'hsl(20 10% 17%)',
        muted: 'hsl(20 15% 90%)',
        mutedForeground: 'hsl(20 10% 40%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(20 10% 17%)',
        border: 'hsl(20 10% 90%)',
        input: 'hsl(20 10% 90%)',
        ring: 'hsl(20 60% 85%)',
      },
      typography: {
        headingFont: 'Noto Serif KR, serif',
        bodyFont: 'Noto Sans KR, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '400',
        bodyWeight: '300',
        letterSpacing: '0.05em',
      },
      visuals: {
        radius: '1rem',
        shadow: '0 4px 20px rgba(0, 0, 0, 0.05)',
        glassEffect: 'soft',
        borderStyle: 'thin',
        borderRadius: 'lg',
      },
      identity: {
        backgroundPattern: 'pattern-minimal-geometric',
        backgroundGradient: 'linear-gradient(180deg, #FCFAF8 0%, #F8F4F0 100%)',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'minimal',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'glass', border: '1px solid hsl(20 10% 90%)', shadow: '0 4px 20px rgba(0,0,0,0.03)' },
        button: { style: 'pill', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'circle' },
        gallery: { style: 'grid', gap: '1rem' },
        rsvp: { style: 'step-by-step' },
        footer: { style: 'modern' },
      },
    },
  },

  // =========================================================================
  // ARTISTIC / CREATIVE
  // =========================================================================
  'newspaper': {
    id: 'newspaper',
    name: 'Newspaper',
    description: 'Classic broadsheet typography. Serif-heavy with a nostalgic newsprint feel.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(0 0% 10%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(0 0% 30%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(40 20% 93%)',
        foreground: 'hsl(0 0% 10%)',
        secondary: 'hsl(40 10% 88%)',
        secondaryForeground: 'hsl(0 0% 20%)',
        muted: 'hsl(40 10% 85%)',
        mutedForeground: 'hsl(0 0% 40%)',
        card: 'hsl(40 20% 95%)',
        cardForeground: 'hsl(0 0% 10%)',
        border: 'hsl(0 0% 70%)',
        input: 'hsl(0 0% 70%)',
        ring: 'hsl(0 0% 20%)',
      },
      typography: {
        headingFont: 'Times New Roman, serif',
        bodyFont: 'Georgia, serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Battambang, serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '0.02em',
      },
      visuals: {
        radius: '0rem',
        shadow: 'none',
        glassEffect: 'none',
        borderStyle: 'thick',
        borderRadius: 'none',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'none',
        texture: 'newsprint-texture',
        accentPattern: '',
        sectionDecoration: 'bold-line',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'flat', border: '2px solid hsl(0 0% 20%)', shadow: 'none' },
        button: { style: 'sharp', transition: 'all 0.1s ease' },
        timeline: { style: 'horizontal', markerStyle: 'diamond' },
        gallery: { style: 'grid', gap: '0.25rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'classic' },
      },
    },
  },
  'editorial': {
    id: 'editorial',
    name: 'Editorial',
    description: 'High-end magazine spreads. Pull quotes, drop caps, and refined whitespace.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(0 0% 15%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(10 60% 40%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(0 0% 97%)',
        foreground: 'hsl(0 0% 15%)',
        secondary: 'hsl(0 0% 92%)',
        secondaryForeground: 'hsl(0 0% 25%)',
        muted: 'hsl(0 0% 88%)',
        mutedForeground: 'hsl(0 0% 45%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(0 0% 15%)',
        border: 'hsl(0 0% 80%)',
        input: 'hsl(0 0% 80%)',
        ring: 'hsl(10 60% 40%)',
      },
      typography: {
        headingFont: 'Playfair Display, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '0.01em',
      },
      visuals: {
        radius: '0rem',
        shadow: '0 2px 10px rgba(0, 0, 0, 0.04)',
        glassEffect: 'none',
        borderStyle: 'thin',
        borderRadius: 'none',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'none',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'bold-line',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'flat', border: 'none', shadow: 'none' },
        button: { style: 'apple', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'diamond' },
        gallery: { style: 'grid', gap: '2rem' },
        rsvp: { style: 'form' },
        footer: { style: 'classic' },
      },
    },
  },
  'luxury-magazine': {
    id: 'luxury-magazine',
    name: 'Luxury Magazine',
    description: 'Vogue-worthy spreads. Bold imagery, elegant layout, and haute couture aesthetics.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(0 0% 7%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(30 80% 45%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(0 0% 100%)',
        foreground: 'hsl(0 0% 10%)',
        secondary: 'hsl(0 0% 92%)',
        secondaryForeground: 'hsl(0 0% 20%)',
        muted: 'hsl(0 0% 88%)',
        mutedForeground: 'hsl(0 0% 45%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(0 0% 10%)',
        border: 'hsl(0 0% 80%)',
        input: 'hsl(0 0% 80%)',
        ring: 'hsl(30 80% 45%)',
      },
      typography: {
        headingFont: 'Playfair Display, Didot, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '700',
        bodyWeight: '300',
        letterSpacing: '0.08em',
      },
      visuals: {
        radius: '0rem',
        shadow: '0 4px 24px rgba(0, 0, 0, 0.06)',
        glassEffect: 'none',
        borderStyle: 'thin',
        borderRadius: 'none',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'none',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'bold-line',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'flat', border: '1px solid hsl(0 0% 80%)', shadow: 'none' },
        button: { style: 'sharp', transition: 'all 0.2s ease' },
        timeline: { style: 'horizontal', markerStyle: 'diamond' },
        gallery: { style: 'grid', gap: '0rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'classic' },
      },
    },
  },
  'watercolor': {
    id: 'watercolor',
    name: 'Watercolor',
    description: 'Soft washes of color. Dreamy, artistic, and fluid like a watercolor painting.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(260 30% 35%)',
        primaryForeground: 'hsl(260 20% 95%)',
        accent: 'hsl(200 50% 65%)',
        accentForeground: 'hsl(260 20% 95%)',
        background: 'hsl(260 30% 97%)',
        foreground: 'hsl(260 20% 15%)',
        secondary: 'hsl(260 40% 92%)',
        secondaryForeground: 'hsl(260 20% 20%)',
        muted: 'hsl(260 25% 88%)',
        mutedForeground: 'hsl(260 15% 45%)',
        card: 'hsl(260 28% 96%)',
        cardForeground: 'hsl(260 20% 15%)',
        border: 'hsl(260 18% 82%)',
        input: 'hsl(260 18% 82%)',
        ring: 'hsl(260 45% 65%)',
      },
      typography: {
        headingFont: 'Cormorant Garamond, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '500',
        bodyWeight: '400',
        letterSpacing: '0.03em',
      },
      visuals: {
        radius: '2rem',
        shadow: '0 8px 32px rgba(100, 80, 120, 0.08)',
        glassEffect: 'soft',
        borderStyle: 'none',
        borderRadius: 'full',
      },
      identity: {
        backgroundPattern: 'pattern-watercolor',
        backgroundGradient: 'linear-gradient(135deg, #F5F0FF 0%, #F0F8FF 50%, #FFF5F0 100%)',
        texture: 'watercolor-texture',
        accentPattern: '',
        sectionDecoration: 'gradient-line',
        particleEffect: 'bubbles',
      },
      components: {
        card: { style: 'glass', border: '1px solid rgba(255,255,255,0.5)', shadow: '0 8px 32px rgba(100,80,120,0.08)' },
        button: { style: 'pill', transition: 'all 0.3s ease' },
        timeline: { style: 'vertical', markerStyle: 'circle' },
        gallery: { style: 'masonry', gap: '1.5rem' },
        rsvp: { style: 'step-by-step' },
        footer: { style: 'modern' },
      },
    },
  },
  'fine-art': {
    id: 'fine-art',
    name: 'Fine Art',
    description: 'Gallery-quality presentation. Minimal frame with maximum visual impact.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(0 0% 10%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(30 60% 50%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(40 20% 96%)',
        foreground: 'hsl(0 0% 10%)',
        secondary: 'hsl(40 15% 90%)',
        secondaryForeground: 'hsl(0 0% 20%)',
        muted: 'hsl(40 10% 85%)',
        mutedForeground: 'hsl(0 0% 40%)',
        card: 'hsl(40 20% 98%)',
        cardForeground: 'hsl(0 0% 10%)',
        border: 'hsl(40 10% 75%)',
        input: 'hsl(40 10% 75%)',
        ring: 'hsl(30 60% 50%)',
      },
      typography: {
        headingFont: 'Cormorant Garamond, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '400',
        bodyWeight: '400',
        letterSpacing: '0.05em',
      },
      visuals: {
        radius: '0rem',
        shadow: 'none',
        glassEffect: 'none',
        borderStyle: 'thick',
        borderRadius: 'none',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'none',
        texture: 'canvas-texture',
        accentPattern: '',
        sectionDecoration: 'thin-line',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'flat', border: '2px solid hsl(0 0% 10%)', shadow: 'none' },
        button: { style: 'sharp', transition: 'all 0.2s ease' },
        timeline: { style: 'horizontal', markerStyle: 'diamond' },
        gallery: { style: 'grid', gap: '2rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'classic' },
      },
    },
  },
  'story-book': {
    id: 'story-book',
    name: 'Story Book',
    description: 'Whimsical and narrative. Like pages from a beautifully illustrated book.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(30 40% 30%)',
        primaryForeground: 'hsl(30 40% 95%)',
        accent: 'hsl(15 80% 55%)',
        accentForeground: 'hsl(30 40% 95%)',
        background: 'hsl(35 40% 95%)',
        foreground: 'hsl(30 40% 15%)',
        secondary: 'hsl(35 30% 88%)',
        secondaryForeground: 'hsl(30 40% 20%)',
        muted: 'hsl(35 25% 82%)',
        mutedForeground: 'hsl(30 30% 40%)',
        card: 'hsl(40 50% 98%)',
        cardForeground: 'hsl(30 40% 15%)',
        border: 'hsl(30 30% 75%)',
        input: 'hsl(30 30% 75%)',
        ring: 'hsl(15 80% 55%)',
      },
      typography: {
        headingFont: 'Cormorant Garamond, Playfair Display, serif',
        bodyFont: 'Cormorant Garamond, serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Battambang, serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.03em',
      },
      visuals: {
        radius: '0.5rem',
        shadow: '0 4px 16px rgba(0, 0, 0, 0.06)',
        glassEffect: 'none',
        borderStyle: 'dashed',
        borderRadius: 'sm',
      },
      identity: {
        backgroundPattern: 'pattern-whimsical',
        backgroundGradient: 'linear-gradient(180deg, #FDF8F0 0%, #F8F0E0 100%)',
        texture: 'paper-texture',
        accentPattern: 'doodle-border',
        sectionDecoration: 'divider-flourish',
        particleEffect: 'petals',
      },
      components: {
        card: { style: 'flat', border: '2px dashed hsl(30 30% 75%)', shadow: '0 4px 16px rgba(0,0,0,0.04)' },
        button: { style: 'pill', transition: 'all 0.2s ease' },
        timeline: { style: 'zigzag', markerStyle: 'circle' },
        gallery: { style: 'grid', gap: '1rem' },
        rsvp: { style: 'form' },
        footer: { style: 'classic' },
      },
    },
  },
  'scrapbook': {
    id: 'scrapbook',
    name: 'Scrapbook',
    description: 'Handmade feel. Tape, stickers, Polaroids, and handwritten notes.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(0 0% 20%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(50 80% 60%)',
        accentForeground: 'hsl(0 0% 20%)',
        background: 'hsl(40 30% 94%)',
        foreground: 'hsl(0 0% 15%)',
        secondary: 'hsl(50 40% 85%)',
        secondaryForeground: 'hsl(0 0% 20%)',
        muted: 'hsl(40 20% 82%)',
        mutedForeground: 'hsl(0 0% 45%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(0 0% 15%)',
        border: 'hsl(0 0% 60%)',
        input: 'hsl(0 0% 60%)',
        ring: 'hsl(50 80% 60%)',
      },
      typography: {
        headingFont: '"Comic Sans MS", "Caveat", cursive',
        bodyFont: '"Caveat", cursive',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '0.02em',
      },
      visuals: {
        radius: '0.25rem',
        shadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
        glassEffect: 'none',
        borderStyle: 'dashed',
        borderRadius: 'sm',
      },
      identity: {
        backgroundPattern: 'pattern-dot-grid',
        backgroundGradient: 'none',
        texture: 'kraft-paper',
        accentPattern: 'tape-border',
        sectionDecoration: 'zigzag-line',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'flat', border: '2px dashed hsl(0 0% 50%)', shadow: '0 4px 12px rgba(0,0,0,0.06)' },
        button: { style: 'sharp', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'circle' },
        gallery: { style: 'stack', gap: '0.5rem' },
        rsvp: { style: 'form' },
        footer: { style: 'classic' },
      },
    },
  },
  'notebook': {
    id: 'notebook',
    name: 'Notebook',
    description: 'School notebook aesthetic. Lined paper, ruled margins, and a studied simplicity.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(220 40% 30%)',
        primaryForeground: 'hsl(220 20% 95%)',
        accent: 'hsl(0 0% 30%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(45 30% 94%)',
        foreground: 'hsl(220 30% 15%)',
        secondary: 'hsl(45 20% 88%)',
        secondaryForeground: 'hsl(220 20% 20%)',
        muted: 'hsl(45 15% 82%)',
        mutedForeground: 'hsl(220 10% 45%)',
        card: 'hsl(45 30% 96%)',
        cardForeground: 'hsl(220 30% 15%)',
        border: 'hsl(220 20% 60%)',
        input: 'hsl(220 20% 60%)',
        ring: 'hsl(220 40% 40%)',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.02em',
      },
      visuals: {
        radius: '0rem',
        shadow: 'none',
        glassEffect: 'none',
        borderStyle: 'thin',
        borderRadius: 'none',
      },
      identity: {
        backgroundPattern: 'pattern-lined-paper',
        backgroundGradient: 'none',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'thin-line',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'flat', border: '1px solid hsl(220 20% 60%)', shadow: 'none' },
        button: { style: 'sharp', transition: 'all 0.15s ease' },
        timeline: { style: 'horizontal', markerStyle: 'dot' },
        gallery: { style: 'grid', gap: '0.5rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'modern' },
      },
    },
  },
  'photo-album': {
    id: 'photo-album',
    name: 'Photo Album',
    description: 'All about the photos. Clean frames, subtle shadows, and a gallery-centric layout.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(0 0% 10%)',
        primaryForeground: 'hsl(0 0% 100%)',
        accent: 'hsl(0 0% 50%)',
        accentForeground: 'hsl(0 0% 100%)',
        background: 'hsl(0 0% 95%)',
        foreground: 'hsl(0 0% 15%)',
        secondary: 'hsl(0 0% 88%)',
        secondaryForeground: 'hsl(0 0% 25%)',
        muted: 'hsl(0 0% 85%)',
        mutedForeground: 'hsl(0 0% 45%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(0 0% 15%)',
        border: 'hsl(0 0% 75%)',
        input: 'hsl(0 0% 75%)',
        ring: 'hsl(0 0% 30%)',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '300',
        bodyWeight: '300',
        letterSpacing: '0.05em',
      },
      visuals: {
        radius: '0.25rem',
        shadow: '0 4px 20px rgba(0, 0, 0, 0.06)',
        glassEffect: 'none',
        borderStyle: 'thin',
        borderRadius: 'sm',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'none',
        texture: 'photo-paper',
        accentPattern: '',
        sectionDecoration: 'thin-line',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'flat', border: '1px solid hsl(0 0% 80%)', shadow: 'none' },
        button: { style: 'apple', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'dot' },
        gallery: { style: 'masonry', gap: '0.5rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'modern' },
      },
    },
  },
  'film-camera': {
    id: 'film-camera',
    name: 'Film Camera',
    description: 'Vintage film aesthetics. Warm tones, grain texture, and cinematic framing.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(28 20% 14%)',
        primaryForeground: 'hsl(28 15% 10%)',
        accent: 'hsl(38 25% 70%)',
        accentForeground: 'hsl(28 15% 10%)',
        background: 'hsl(30 40% 95%)',
        foreground: 'hsl(28 15% 10%)',
        secondary: 'hsl(35 20% 85%)',
        secondaryForeground: 'hsl(28 15% 10%)',
        muted: 'hsl(30 20% 90%)',
        mutedForeground: 'hsl(28 10% 40%)',
        card: 'hsl(30 40% 96%)',
        cardForeground: 'hsl(28 15% 10%)',
        border: 'hsl(30 20% 80%)',
        input: 'hsl(30 20% 80%)',
        ring: 'hsl(38 25% 70%)',
      },
      typography: {
        headingFont: 'Playfair Display, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.03em',
      },
      visuals: {
        radius: '0rem',
        shadow: '0 8px 30px rgba(0, 0, 0, 0.08)',
        glassEffect: 'none',
        borderStyle: 'thick',
        borderRadius: 'none',
      },
      identity: {
        backgroundPattern: 'pattern-film-grain',
        backgroundGradient: 'linear-gradient(180deg, #F5EDE0 0%, #EDE0D0 100%)',
        texture: 'film-grain',
        accentPattern: 'border-film-frame',
        sectionDecoration: 'thin-line',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'flat', border: '2px solid hsl(30 20% 70%)', shadow: '0 8px 30px rgba(0,0,0,0.06)' },
        button: { style: 'sharp', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'diamond' },
        gallery: { style: 'grid', gap: '0rem' },
        rsvp: { style: 'form' },
        footer: { style: 'classic' },
      },
    },
  },
  'vintage': {
    id: 'vintage',
    name: 'Vintage',
    description: 'Nostalgic warmth. Sepia tones, classic patterns, and a timeless feel.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(15 40% 30%)',
        primaryForeground: 'hsl(30 40% 95%)',
        accent: 'hsl(30 50% 60%)',
        accentForeground: 'hsl(15 40% 15%)',
        background: 'hsl(30 40% 92%)',
        foreground: 'hsl(15 40% 15%)',
        secondary: 'hsl(30 30% 85%)',
        secondaryForeground: 'hsl(15 40% 20%)',
        muted: 'hsl(30 25% 80%)',
        mutedForeground: 'hsl(15 30% 40%)',
        card: 'hsl(35 50% 95%)',
        cardForeground: 'hsl(15 40% 15%)',
        border: 'hsl(30 20% 70%)',
        input: 'hsl(30 20% 70%)',
        ring: 'hsl(15 40% 40%)',
      },
      typography: {
        headingFont: 'Playfair Display, serif',
        bodyFont: 'Cormorant Garamond, serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Battambang, serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.05em',
      },
      visuals: {
        radius: '0.5rem',
        shadow: '0 4px 16px rgba(60, 40, 20, 0.08)',
        glassEffect: 'none',
        borderStyle: 'double',
        borderRadius: 'sm',
      },
      identity: {
        backgroundPattern: 'pattern-vintage-floral',
        backgroundGradient: 'linear-gradient(180deg, #F5EDE0 0%, #EDE3D0 100%)',
        texture: 'vintage-paper',
        accentPattern: 'vintage-border',
        sectionDecoration: 'divider-flourish',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'luxury', border: '2px solid hsl(30 20% 70%)', shadow: '0 4px 16px rgba(60,40,20,0.06)' },
        button: { style: 'pill', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'diamond' },
        gallery: { style: 'grid', gap: '1rem' },
        rsvp: { style: 'form' },
        footer: { style: 'classic' },
      },
    },
  },
  'cinema': {
    id: 'cinema',
    name: 'Cinema',
    description: 'Widescreen drama. Letterbox framing, cinematic color grading, and epic typography.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(220 30% 8%)',
        primaryForeground: 'hsl(210 30% 95%)',
        accent: 'hsl(38 40% 60%)',
        accentForeground: 'hsl(210 30% 95%)',
        background: 'hsl(220 35% 6%)',
        foreground: 'hsl(210 30% 95%)',
        secondary: 'hsl(215 20% 18%)',
        secondaryForeground: 'hsl(210 30% 95%)',
        muted: 'hsl(218 15% 25%)',
        mutedForeground: 'hsl(210 10% 60%)',
        card: 'hsl(220 30% 10%)',
        cardForeground: 'hsl(210 30% 95%)',
        border: 'hsl(215 25% 30%)',
        input: 'hsl(215 20% 25%)',
        ring: 'hsl(38 40% 60%)',
      },
      typography: {
        headingFont: 'Playfair Display, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '700',
        bodyWeight: '400',
        letterSpacing: '0.05em',
      },
      visuals: {
        radius: '0rem',
        shadow: '0 15px 50px rgba(0, 0, 0, 0.8)',
        glassEffect: 'strong',
        borderStyle: 'none',
        borderRadius: 'none',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'radial-gradient(ellipse at center, #1a1a2e 0%, #0a0a12 100%)',
        texture: 'film-grain',
        accentPattern: '',
        sectionDecoration: 'cinematic-line',
        particleEffect: 'none',
      },
      components: {
        card: { style: 'glass', border: '1px solid rgba(255,255,255,0.05)', shadow: '0 20px 60px rgba(0,0,0,0.5)' },
        button: { style: 'sharp', transition: 'all 0.3s ease' },
        timeline: { style: 'horizontal', markerStyle: 'diamond' },
        gallery: { style: 'carousel', gap: '0rem' },
        rsvp: { style: 'minimal' },
        footer: { style: 'modern' },
      },
    },
  },

  // =========================================================================
  // NATURE / ENVIRONMENTAL
  // =========================================================================
  'forest': {
    id: 'forest',
    name: 'Forest',
    description: 'Rich, earthy, and grounded. Deep greens and natural wood tones.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(158 45% 28%)',
        primaryForeground: 'hsl(42 40% 96%)',
        accent: 'hsl(38 72% 52%)',
        accentForeground: 'hsl(158 50% 12%)',
        background: 'hsl(155 30% 96%)',
        foreground: 'hsl(158 40% 14%)',
        secondary: 'hsl(150 25% 90%)',
        secondaryForeground: 'hsl(158 35% 20%)',
        muted: 'hsl(150 18% 85%)',
        mutedForeground: 'hsl(158 15% 40%)',
        card: 'hsl(42 40% 97%)',
        cardForeground: 'hsl(158 40% 14%)',
        border: 'hsl(158 20% 78%)',
        input: 'hsl(158 20% 78%)',
        ring: 'hsl(38 72% 52%)',
      },
      typography: {
        headingFont: 'Cormorant Garamond, serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '600',
        bodyWeight: '400',
        letterSpacing: '0.02em',
      },
      visuals: {
        radius: '0.75rem',
        shadow: '0 8px 30px rgba(0, 60, 30, 0.08)',
        glassEffect: 'none',
        borderStyle: 'thin',
        borderRadius: 'md',
      },
      identity: {
        backgroundPattern: 'pattern-leaves',
        backgroundGradient: 'linear-gradient(180deg, #F0F7F3 0%, #E8F0EB 100%)',
        texture: 'wood-texture',
        accentPattern: 'leaf-border',
        sectionDecoration: 'natural-line',
        particleEffect: 'petals',
      },
      components: {
        card: { style: 'luxury', border: '1px solid hsl(158 20% 78%)', shadow: '0 8px 30px rgba(0,60,30,0.06)' },
        button: { style: 'pill', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'circle' },
        gallery: { style: 'grid', gap: '1rem' },
        rsvp: { style: 'form' },
        footer: { style: 'classic' },
      },
    },
  },
  'beach': {
    id: 'beach',
    name: 'Beach',
    description: 'Sun, sand, and sea breeze. Bright blues, warm sands, and casual elegance.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(208 30% 22%)',
        primaryForeground: 'hsl(210 20% 17%)',
        accent: 'hsl(28 80% 65%)',
        accentForeground: 'hsl(210 20% 17%)',
        background: 'hsl(25 60% 98%)',
        foreground: 'hsl(210 20% 17%)',
        secondary: 'hsl(30 70% 85%)',
        secondaryForeground: 'hsl(210 20% 17%)',
        muted: 'hsl(28 50% 90%)',
        mutedForeground: 'hsl(210 15% 40%)',
        card: 'hsl(0 0% 100%)',
        cardForeground: 'hsl(210 20% 17%)',
        border: 'hsl(28 40% 90%)',
        input: 'hsl(28 40% 90%)',
        ring: 'hsl(28 80% 65%)',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '300',
        bodyWeight: '300',
        letterSpacing: '0.04em',
      },
      visuals: {
        radius: '1.5rem',
        shadow: '0 8px 32px rgba(30, 60, 100, 0.08)',
        glassEffect: 'soft',
        borderStyle: 'none',
        borderRadius: 'lg',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'linear-gradient(180deg, #E8F4F8 0%, #FEF9F0 50%, #FDF5E6 100%)',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'wave-line',
        particleEffect: 'bubbles',
      },
      components: {
        card: { style: 'glass', border: '1px solid rgba(255,255,255,0.6)', shadow: '0 8px 32px rgba(30,60,100,0.06)' },
        button: { style: 'pill', transition: 'all 0.2s ease' },
        timeline: { style: 'horizontal', markerStyle: 'circle' },
        gallery: { style: 'masonry', gap: '1.5rem' },
        rsvp: { style: 'form' },
        footer: { style: 'modern' },
      },
    },
  },
  'flower-garden': {
    id: 'flower-garden',
    name: 'Flower Garden',
    description: 'Romantic and blooming. Soft pinks, lavender, and floral motifs everywhere.',
    category: 'Artistic',
    tokens: {
      colors: {
        primary: 'hsl(340 30% 24%)',
        primaryForeground: 'hsl(340 20% 18%)',
        accent: 'hsl(350 40% 65%)',
        accentForeground: 'hsl(340 20% 18%)',
        background: 'hsl(345 50% 98%)',
        foreground: 'hsl(340 20% 18%)',
        secondary: 'hsl(350 50% 80%)',
        secondaryForeground: 'hsl(340 20% 18%)',
        muted: 'hsl(345 30% 90%)',
        mutedForeground: 'hsl(340 15% 45%)',
        card: 'hsl(345 50% 97%)',
        cardForeground: 'hsl(340 20% 18%)',
        border: 'hsl(340 25% 88%)',
        input: 'hsl(340 25% 88%)',
        ring: 'hsl(350 40% 65%)',
      },
      typography: {
        headingFont: 'Playfair Display, serif',
        bodyFont: 'Cormorant Garamond, serif',
        khmerHeadingFont: 'Moul, serif',
        khmerBodyFont: 'Battambang, serif',
        headingWeight: '500',
        bodyWeight: '400',
        letterSpacing: '0.04em',
      },
      visuals: {
        radius: '2rem',
        shadow: '0 10px 40px rgba(180, 80, 120, 0.08)',
        glassEffect: 'soft',
        borderStyle: 'none',
        borderRadius: 'full',
      },
      identity: {
        backgroundPattern: 'pattern-floral',
        backgroundGradient: 'linear-gradient(180deg, #FDF5F7 0%, #F8EDF2 100%)',
        texture: '',
        accentPattern: 'floral-border',
        sectionDecoration: 'divider-flourish',
        particleEffect: 'petals',
      },
      components: {
        card: { style: 'glass', border: '1px solid rgba(255,200,210,0.4)', shadow: '0 10px 40px rgba(180,80,120,0.06)' },
        button: { style: 'pill', transition: 'all 0.2s ease' },
        timeline: { style: 'vertical', markerStyle: 'circle' },
        gallery: { style: 'masonry', gap: '1.5rem' },
        rsvp: { style: 'form' },
        footer: { style: 'classic' },
      },
    },
  },

  // =========================================================================
  // GLASS / MODERN EFFECTS
  // =========================================================================
  'glassmorphism': {
    id: 'glassmorphism',
    name: 'Glassmorphism',
    description: 'Frosted glass, blur effects, and translucent layers for a futuristic feel.',
    category: 'Modern',
    tokens: {
      colors: {
        primary: 'hsl(210 40% 24%)',
        primaryForeground: 'hsl(210 20% 10%)',
        accent: 'hsl(200 40% 65%)',
        accentForeground: 'hsl(210 20% 10%)',
        background: 'hsl(210 50% 97%)',
        foreground: 'hsl(210 20% 10%)',
        secondary: 'hsl(200 30% 85%)',
        secondaryForeground: 'hsl(210 20% 10%)',
        muted: 'hsl(210 25% 90%)',
        mutedForeground: 'hsl(210 15% 45%)',
        card: 'hsl(0 0% 90%)',
        cardForeground: 'hsl(210 20% 10%)',
        border: 'hsl(210 20% 80%)',
        input: 'hsl(210 20% 80%)',
        ring: 'hsl(200 40% 65%)',
      },
      typography: {
        headingFont: 'Inter, sans-serif',
        bodyFont: 'Inter, sans-serif',
        khmerHeadingFont: 'Kantumruy Pro, sans-serif',
        khmerBodyFont: 'Kantumruy Pro, sans-serif',
        headingWeight: '500',
        bodyWeight: '300',
        letterSpacing: '-0.01em',
      },
      visuals: {
        radius: '1.5rem',
        shadow: '0 20px 50px rgba(0, 0, 0, 0.1)',
        glassEffect: 'frosted',
        borderStyle: 'thin',
        borderRadius: 'lg',
      },
      identity: {
        backgroundPattern: '',
        backgroundGradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        texture: '',
        accentPattern: '',
        sectionDecoration: 'gradient-line',
        particleEffect: 'bubbles',
      },
      components: {
        card: { style: 'glass', border: '1px solid rgba(255,255,255,0.3)', shadow: '0 24px 60px rgba(0,0,0,0.15)' },
        button: { style: 'glass', transition: 'all 0.3s ease' },
        timeline: { style: 'vertical', markerStyle: 'dot' },
        gallery: { style: 'grid', gap: '1.5rem' },
        rsvp: { style: 'step-by-step' },
        footer: { style: 'modern' },
      },
    },
  },
};